### ISSUE TITLE
do you have some othe model's code？such as HA/ARIMA/SVR?

### ISSUE THREAD

**Issue by plaxkk** [lehaifeng/T-GCN#1]

**Comment by lehaifeng** [comment]
We will upload them soon.

**Comment by chaojidaxingxin** [comment]
I really look forward to your upload of the baseline model, which will help me a lot. 
Thank you very much！

**Comment by lehaifeng** [comment]
Thanks for your attention. 
We will upload it within one week.

**Comment by chaojidaxingxin** [comment]
Thank you~

**Comment by flowingrain** [comment]
I think there is something wrong with the HA model in baselines.py.
ValueError: Found input variables with inconsistent numbers of samples: [1167, 389]

**Comment by cindy-lihan** [comment]
> I think there is something wrong with the HA model in baselines.py.
> ValueError: Found input variables with inconsistent numbers of samples: [1167, 389]

Have you solved this problem? I have the same problem.Thanks.
