### ISSUE TITLE
tgcn model

### ISSUE THREAD

**Issue by fsgdrq** [lehaifeng/T-GCN#10]
Hi , I have read your paper and try to understand the model but I got some problems. i am not quite understand that why the state part (which I thought that is a gru thing) , would also be send into the graph conv function?  I am just a rookie on gcn and gru , hope I could get some help, thanks.

**Comment by lehaifeng** [comment]
Hi fsgdrq
Thanks for your attention.

In the implementation, we use the graph convolution to replace the linear calculation in GRU to obtain spatial features. When information at every moment is updated, spatial information can be considered.

**Comment by fsgdrq** [comment]
Hi again ,
thanks for your patience!


as you use the gc to replace linear in GRU, I wonder what is the difference between this and GCN+GRU(input the data into a two-GCN layer and get the output as the input to GRU) Is it the same? thanks.

**Comment by JarvisKevin** [comment]
Hi @fsgdrq,  I also have this question, have you figured it out?

**Comment by leoncesc** [comment]
> Hi @fsgdrq, I also have this question, have you figured it out?
@fsgdrq @JarvisKevin 
Hi, I think the calculation in a GRU cell also considers the graph structure, so the linear calculation in GRU seems to use the adjacney matrix of graph. Don't know what is the difference in result between this calculation and GCN + GRU. At least, we need to write the code of this gc GRU.
