### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by dove-whispers** [lehaifeng/T-GCN#109]
when i clone this T-GCN-PyTorch project and run `pip install -r requirements.txt` but meet `AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'` , why and how to fix it
![image](https://github.com/user-attachments/assets/8ae90a91-76cc-40d1-9a6d-16d08bf07f51)

**Comment by want1023** [comment]
我也遇到这个问题了，请问一下这个怎么解决
