### ISSUE TITLE
Use TGCN for dynamic graphs

### ISSUE THREAD

**Issue by fatemehteimury** [lehaifeng/T-GCN#12]
Hi, It would be so nice if you specify how we can use TGC for dynamic graphs with different adjacency matrix and feature matrix in each snapshot?

**Comment by lehaifeng** [comment]
HI fatemehteimury, thanks for your attention.
Considering dynamic graphs in GCN is a challenge issue which we are working on.
We will release our work after we finish it. 
You can also refer to this link for some insights: 
https://arxiv.org/abs/1704.06199

**Comment by fatemehteimury** [comment]
Thanks for your response. 
regards, 
Fatemeh
