### ISSUE TITLE
how to restore pre-trained meta model and pass it's weights and biases to the optimizer?

### ISSUE THREAD

**Issue by TheLastPixie** [lehaifeng/T-GCN#13]
Hey Mr.Haifeng

I trained a model on a specific dataset and saved it as a meta, I want to restore the model and use its weights and biases on another dataset the code isn't mine but I'm trying to restore the architecture after it was saved to metafile.

I tried many workarounds and ran into numerous errors I can't post all of them here, is it possible to do transfer learning using this architecture, I can use this architecture on any new dataset, but I can't reuse the trained model variables on another data set.
Should I save operations done in the original graph and then call them in the new code.? 

This is the code I'm using to restore weights and biases as well as placeholders.

```
sess=tf.Session()    
saver2 = tf.train.import_meta_graph('TGCNpretrain.model.meta')
saver2.restore(sess, tf.train.latest_checkpoint('./'))
print("model restored")
graph = tf.get_default_graph()
print(tf.compat.v1.trainable_variables())
print("------------------------------------------------------------------------------")

weights ={
    'out2':[v for v in tf.trainable_variables() if v.name == "weight_o:0"][0]}
biases ={
    'out2':[v for v in tf.trainable_variables() if v.name == "bias_o:0"][0]}
###### placeholders ######
inputs = tf.get_default_graph().get_tensor_by_name('inputs1:0')
labels = tf.get_default_graph().get_tensor_by_name('labels1:0')

y_pred = inputs

###### optimizer ######
Lreg = sum(tf.nn.l2_loss(tf_var) for tf_var in tf.trainable_variables())

label = tf.reshape(labels, [-1,num_nodes])
##loss
loss = tf.reduce_mean(tf.nn.l2_loss(y_pred-label) + Lreg)
##rmse
error = tf.sqrt(tf.reduce_mean(tf.square(y_pred-label)))
optimizer = tf.train.AdamOptimizer(lr).minimize(loss)


```
I don't know what to pass to the optimizer, loss and error equations, I tried several combinations as shaping error all the time 
`ValueError: Shapes must be equal rank, but are 2 and 1
	From merging shape 4 with other shapes. for 'Rank/packed' (op: 'Pack')`
I also run this error very often 
`    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'weight_o/Adam'`

**Comment by lehaifeng** [comment]
HI, TheLastPixie. Thanks for your attention.

Here is my answer. For the same dataset, you can save and reuse the model; while for different datasets, the model can only be reused when the shape of the input data is the same. If the shape of the input data is different, the model is not callable. You must re-train your own model.
