### ISSUE TITLE
GCN code

### ISSUE THREAD

**Issue by chenk-gd** [lehaifeng/T-GCN#14]
hi, thank you for sharing.  I've studied your paper and code and have some questions:
1.  according your paper, the gcn model is expressed as:
     f(X, A) = act(A Relu (AXW0) W1)

     but in tgcn.py,  it seems like:
    f(X, A) = AXW0 + b0

     in gcn.py, it looks like:
     f(X, A) = act(AXW0)W1    (act is tanh by default)

     do  I misunderstand it ?

2.  the following code in gcn.py & tgcn.py:
          for adj in self._adj:
                x1 = tf.sparse_tensor_dense_matmul(adj, x0)
     in your implementation, the self._adj is a list that contains only one element, that's OK. 
     but if it contains more than one element?  the loop seems to have no effect, it  only uses
     the last element.

**Comment by lehaifeng** [comment]
HI chenk-gd, thanks for your attention.

Firstly, we use a one-layer GCN model in our code, that is, f(X, A) = act(AXW0). The f(X, A) = act(AXW0)W1 represents a one-layer model and a full-connected layer. In our implementation, we use a static road network, so there was only one adjacency matrix. If you want to use a dynamic road network, it would be completely different and more than just adding the number of adjacency matrices and iterating.

**Comment by bmkor** [comment]
Would like to share my run on the GCN model for the `los` data and predicting 15-min speed (i.e. `pre_len=3`). I tried both 1-layer and 2-layer GCN, following the code in this repository. 

Both layers got similar results as below. The validation RMSE stayed high (around 14) and refused to go down.

<img width="651" alt="Screenshot 2019-10-28 at 1 13 39 PM" src="https://user-images.githubusercontent.com/12775449/67653733-abcfce00-f985-11e9-8b83-238dcbb3279f.png">

Not sure what have I missed. Mind shading light? Thanks.

**Comment by bmkor** [comment]
Finally, I rewrote the GCN part without the approximation on \tilde{A} but following Michael Defferrard's [paper](https://arxiv.org/abs/1606.09375) in using Chebyshev polynomials with K = 2 and obtained a promising result as below.

![test_oneday](https://user-images.githubusercontent.com/12775449/68087946-7e0eeb80-fe95-11e9-8106-348754ab2280.jpg)

**Comment by dgssession** [comment]
> 最后，我改写了GCN部分，没有在\ tilde {A}上近似，但是按照Michael Defferrard的[论文](https://arxiv.org/abs/1606.09375)，使用了K = 2的Chebyshev多项式，并获得了令人满意的结果，如下所示。
> 
> ![test_oneday](https://user-images.githubusercontent.com/12775449/68087946-7e0eeb80-fe95-11e9-8106-348754ab2280.jpg)

I also have this problem, can you share your code? Thakns.

**Comment by DGShub** [comment]
> Finally, I rewrote the GCN part without the approximation on \tilde{A} but following Michael Defferrard's [paper](https://arxiv.org/abs/1606.09375) in using Chebyshev polynomials with K = 2 and obtained a promising result as below.
> 
> ![test_oneday](https://user-images.githubusercontent.com/12775449/68087946-7e0eeb80-fe95-11e9-8106-348754ab2280.jpg)

I also have this problem, can you share your code? Thakns.

**Comment by bmkor** [comment]
> > Finally, I rewrote the GCN part without the approximation on \tilde{A} but following Michael Defferrard's [paper](https://arxiv.org/abs/1606.09375) in using Chebyshev polynomials with K = 2 and obtained a promising result as below.
> > ![test_oneday](https://user-images.githubusercontent.com/12775449/68087946-7e0eeb80-fe95-11e9-8106-348754ab2280.jpg)
> 
> I also have this problem, can you share your code? Thakns.

Yes. I'll post my code in my github later after cleansing. It may take a while. The codes are written in TF2.0. @dgssession
