### ISSUE TITLE
graph convolution process in `tgcn` cell 

### ISSUE THREAD

**Issue by bmkor** [lehaifeng/T-GCN#18]
Hi @lehaifeng,

Once again, thanks for pasting the code here. I got a question on the graph convolution when I read `tgcn.py`. 

https://github.com/lehaifeng/T-GCN/blob/24fc8d8211581d51ddbcf3f6ee7a5269ea7129b8/tgcn.py#L53-L62

As above, it seems to me that the convolution is 

![ql_36361ffe3511d210798d4cdb1415a82f_l3](https://user-images.githubusercontent.com/12775449/65400615-d1e9d780-ddf5-11e9-86e7-d3c2728b847a.png)

instead of 

![ql_9830f373b0708043aba2483a7353524e_l3](https://user-images.githubusercontent.com/12775449/65400644-f776e100-ddf5-11e9-9365-16cf910b2e6c.png)

similar for `r_t` and `c_t`, as written in the paper (https://arxiv.org/pdf/1811.05320.pdf). Not sure if I am misunderstood. Mind throwing some lights to me? Thanks in advance.

**Comment by JarvisKevin** [comment]
I am also puzzle by this trouble @bmkor . And, does the function _gc match with the f(A,X)?

**Comment by JarvisKevin** [comment]
Hi @bmkor, have you solved your problem? and i have any other question, when i replace the _gc to _linear (e.g. GRU) in the tgcn.py, i found that _linear outperforms to _gc.

**Comment by bmkor** [comment]
Hi @JarvisKevin. I ended up with using other GCN to solve the problem. You may refer to [here](https://github.com/lehaifeng/T-GCN/issues/14) if you are interested.

**Comment by JarvisKevin** [comment]
@bmkor I also turned to the cheb gcn (K=3) too, it works better.

**Comment by bmkor** [comment]
@JarvisKevin cool. In fact, I would try T-gcn (chebyshev) when I am less busy.
