### ISSUE TITLE
关于遇到的一些问题

### ISSUE THREAD

**Issue by Lzw-CUG** [lehaifeng/T-GCN#19]
你好，我仔细阅读了这篇论文（我就不用英文了）
主要想请教两个问题，
1.    trainX, trainY, testX, testY = [], [], [], []
    for i in range(len(train_data) - seq_len - pre_len):
        a = train_data[i: i + seq_len + pre_len]
        trainX.append(a[0 : seq_len])
        trainY.append(a[seq_len : seq_len + pre_len])
    for i in range(len(test_data) - seq_len -pre_len):
        b = test_data[i: i + seq_len + pre_len] 
        testX.append(b[0 : seq_len])
        testY.append(b[seq_len : seq_len + pre_len])
第一个是这段代码中的实际意义我不是很清楚，我只能发现可以解决数组越界这一个问题，所以想请教一下代码的实际含义。
2.第二个是论文中的两个数据集都是预测了之后15min，30min，45min以及60min的数据，但两个数据集的时间间隔是不一样的，Los-loop数据集的时间间隔是5min。以15min为例，这样是可以预测到后3个时间间隔的速度么？

**Comment by tinmodeHuang** [comment]
take an example of los_data set
```python
def preprocess_data(data, time_len, rate, seq_len, pre_len):# ((2016,207),2016,0.8,12,3)
    train_size = int(time_len * rate) # 1728
    train_data = data[0:train_size] # data[0:1728,207]
    test_data = data[train_size:time_len] # data[1728:2016,207]
    
    trainX, trainY, testX, testY = [], [], [], []
    for i in range(len(train_data) - seq_len - pre_len): # range(1713)
        a = train_data[i: i + seq_len + pre_len] #train_data[i:i+15,207]
        trainX.append(a[0 : seq_len]) # a[12,207]
        trainY.append(a[seq_len : seq_len + pre_len]) # a[3,207]
    for i in range(len(test_data) - seq_len -pre_len): # range(273)
        b = test_data[i: i + seq_len + pre_len] # test_data[i:i+15,207]
        testX.append(b[0 : seq_len]) # b[12,207]
        testY.append(b[seq_len : seq_len + pre_len]) # b[3,207]
      
    trainX1 = np.array(trainX) # (1713,12,207)
    trainY1 = np.array(trainY) # (1713,3,207)
    testX1 = np.array(testX) # (273,12,207)
    testY1 = np.array(testY) # (273,3,207)
    return trainX1, trainY1, testX1, testY1
```
I can only help you so much
