### ISSUE TITLE
How to deal with time deviation？

### ISSUE THREAD

**Issue by yuntunmian3** [lehaifeng/T-GCN#22]
Thanks again your meaningful article and code.
I have a question here: We know that the speed of a point depends on the speed of the previous points. For example, a car drive into expressway and pass the point A at time t, and it will effect the point B at time t+Δt. So there is a time deviation Δt between A and B. So after you capture the spatial feature by GCN, will the time deviation impress the effect of LSTM ？Is it necessary to involve attention mechanism like GAT to solve this problem? Looking forward to your opinion.

**Comment by lehaifeng** [comment]
HI yuntunmian3, Thanks for your attention.
En, Yeah, we use GRU as a temporal feature learner just like LSTM, if I have understood your question right. Attention can be a component in our structure, which we have done. We will post it soon.

Thanks

**Comment by yuntunmian3** [comment]
> HI yuntunmian3, Thanks for your attention.
> En, Yeah, we use GRU as a temporal feature learner just like LSTM, if I have understood your question right. Attention can be a component in our structure, which we have done. We will post it soon.
> 
> Thanks

COOL! I look forward to your code to help me understand GCN better. By the way，it's my mistake to say LSTM instead of GRU:)
