### ISSUE TITLE
How do you get the adjacency matrix of sz or los？

### ISSUE THREAD

**Issue by lilixu023** [lehaifeng/T-GCN#24]
hi mr le
  thank u for your contribution of the open source code and data ：D
 I am doing traffic speed predication of changsha now，but I met a problem when i process the road network data。。。can i ask how do you get the adjacency matrix of sz？thank u very much！！！

**Comment by gegebule** [comment]
I have the same problem as you. Have you solved this problem？Do you know how to get the adjacency matrix? thank you very much

**Comment by woshixiangtang** [comment]
I also have the same problem！How did you solve this problem？or do you have any alternative data sets and processing methods? this is very important for me ,thank you very much.

**Comment by ThomasAFink** [comment]
To create your own matrix this may help: https://github.com/ThomasAFink/osmnx_adjacency_matrix_for_graph_convolutional_networks
