### ISSUE TITLE
请问您是否保留有原始的深圳数据集呢？

### ISSUE THREAD

**Issue by woshixiangtang** [lehaifeng/T-GCN#25]

**Comment by lehaifeng** [comment]
We downloaded the dataset from the Internet.
I didn't get a license to offer the dataset. Sorry

**Comment by woshixiangtang** [comment]
> We downloaded the dataset from the Internet.
> I didn't get a license to offer the dataset. Sorry

Hello ！ Thanks for replying. I have a question in the los_adj.csv, I would like to ask what does the decimal in this csv file mean? Is it not only 0 and 1 that the two points are connected?

**Comment by lehaifeng** [comment]
HI woshixiangtang, thanks for your attention.
The 0 and 1 are used indict if two nodes are connected. We treat the traffic as the feature of a node.

**Comment by woshixiangtang** [comment]
> HI woshixiangtang, thanks for your attention.
> The 0 and 1 are used indict if two nodes are connected. We treat the traffic as the feature of a node.

Yeah,  The 0 and 1 are used indict if two nodes are connected in the adjacency matrix. But I want to ask what does the decimal in  the adjacency matrix mean? For example ,  in the los_adj.csv，inclluding 0 and 1,there are also many decimals such as 0.717438, what's the meaning of 0.717438?

**Comment by woshixiangtang** [comment]
Another question,What is the ‘los_adj.pkl' file  used for?I don't understand what the content of this file means。
 I am a beginner for GCN,Could you explain it? Thank you very much

**Comment by MasterWall** [comment]
I have the same question, why the adj matrix exist such as the 0.717438...

**Comment by zaibian** [comment]
also,I have the same question, why the adj matrix exist such as the 0.717438...

**Comment by RowanLiu97** [comment]
also,I have the same question, why the adj matrix exist such as the 0.717438...
