### ISSUE TITLE
代码里面看只有一层GCN?

### ISSUE THREAD

**Issue by sqcao6** [lehaifeng/T-GCN#29]
作者代码里是只用了一层GCN吗？

**Comment by lehaifeng** [comment]
HI, sqcao6, thanks for your attention.

Yeah, one layer GCN is the best according to metrics.  So we release the best one.
In fact, with deeper GCN, the neighborhood will diffuse to the whole network.

**Comment by MrYaoH** [comment]
Hello, author.
I have an another question about GCN layer. Is the layer simply multiplied by the adjacency matrix without weight matrix?
