### ISSUE TITLE
can't reproduce your result

### ISSUE THREAD

**Issue by plaxkk** [lehaifeng/T-GCN#3]
![image](https://user-images.githubusercontent.com/17794023/50438750-499fda00-092a-11e9-8eda-447871ccda26.png)
tgcn_sz_lr0.001_batch64_unit100_seq10_pre1_epoch1

**Comment by lehaifeng** [comment]
HI, thanks for your feedback.

Was your model convergence? It seems only one epoch in your experiment.

**Comment by plaxkk** [comment]
I got it, I saw that the training epoch is 1 in the out folder.So I compared to it.
I read your paper,the training epoch is 2000 just now.
To reproduce the result, maybe you can note the parameter in readMe in case of misunderstanding?

**Comment by lehaifeng** [comment]
Thanks for suggestions.
We will improve it in the next submission.

**Comment by plaxkk** [comment]
and another suggestion! 
you should use seed function in tensorflow and numpy to reproduce
