### ISSUE TITLE
The link of los-loop dataset that collected in the highway of Los Angeles County.

### ISSUE THREAD

**Issue by huangqianfirst** [lehaifeng/T-GCN#30]
Thanks for your work. Would you please give me the link of los-loop dataset that collected in the highway of Los Angeles County ?

**Comment by lehaifeng** [comment]
HI, thanks for your attention.

It is from METR-LA dataset. This dataset contains 207 sensors and collects 4 months of data ranging from Mar 1st 2012 to Jun 30th 2012 for the experiment. 70% of data is used for training, 20% is used for testing while the remaining 10% for validation. Traffic speed readings are aggregated into 5 minutes windows, and Z-Score is applied for normalization.
