### ISSUE TITLE
I run the A3T-GCN.py find a wrong

### ISSUE THREAD

**Issue by MasterWall** [lehaifeng/T-GCN#32]
The pycharm display a bug, what should I do?
    pred,ttts,ttto = GRU(inputs, weights, bias)
NameError: name 'GRU' is not defined

<img width="99" alt="Snipaste_2020-08-01_08-23-58" src="https://user-images.githubusercontent.com/49579828/89089645-e95bfe80-d3d0-11ea-995a-17ed3692edda.png">
<img width="408" alt="1" src="https://user-images.githubusercontent.com/49579828/89089663-fc6ece80-d3d0-11ea-86f9-79bc7861f829.png">

**Comment by lehaifeng** [comment]
It seems that the problem is caused by the wrong file path.
You should check it.

Best

**Comment by Chethan-Babu-stack** [comment]
I'm facing the same issue. Could you please tell what is the issue.
