### ISSUE TITLE
how can I run baseline about gru and gcn？

### ISSUE THREAD

**Issue by upczxy** [lehaifeng/T-GCN#34]
I want to compare GRU and GCN. Can I expose this part of the code？thank you

**Comment by lehaifeng** [comment]
Hi zxy1111, thanks for your attention.
GRU and GCN were included in the file named "Baseline".
Enjoy!

**Comment by upczxy** [comment]
Sorry. But I can not find it.  I only find HA , SVR and ARIMA in the baseline file.

**Comment by lehaifeng** [comment]
Sorry, my mistake.
Please refer to /T-GCN/gcn.py and /T-GCN/gru.py

**Comment by xingyaxuan** [comment]
您好，请问GCN函数没有return，调用报错如何解决?
