### ISSUE TITLE
Can T-GCN deal with multivariate time series features?

### ISSUE THREAD

**Issue by PanZiwei** [lehaifeng/T-GCN#38]
Hi, 
I would really appreciate it if you can help with the issues:
1. It seems that GCN_LSTM is a univariate time series forecasting method. Is it possible to use multivariate time series features to build the model? ( I found relevant issue on #21 but failed to find the knowledge graph)

2. Can non-time series feature be added to the model? 

3. So the architecture comprises of a stack of N1 Graph Convolutional layers followed by N2 LSTM layers, a Dropout layer, and a Dense layer. Am I correct?

Thank you so much for your help!

**Comment by Chethan-Babu-stack** [comment]
Yes, T-GCN can totally work for multivariate time series data.

1. GCN_LSTM is multivariate
2. Please explain more what is ur question
3. Gated Recurrent Units are used in the code as far as I have seen, not LSTM.
