### ISSUE TITLE
万分感谢！

### ISSUE THREAD

**Issue by linchuanXu** [lehaifeng/T-GCN#40]
您写的代码非常优美，上传的内容也非常完整，我已经复现！让我这个新手学到了很多，非常感谢您。

**Comment by RowanLiu97** [comment]
Hello! 
I have a question for you.
Did you notice the data file los_adj.csv. In the los_adj.csv，inclluding 0 and 1,there are also many decimals such as 0.717438, what's the meaning of 0.717438?
Looking forward to your reply, Thank you
