### ISSUE TITLE
关于sz_speed数据集的问题

### ISSUE THREAD

**Issue by qiubin1997** [lehaifeng/T-GCN#43]
你好，乐先生！请教你一个问题，你在论文中提到的关于sz_speed数据集中，说到“每行代表一条路；每一列是不同时间段道路上的交通速度。我们每15分钟汇总一次每条路上的交通速度“，但我在深圳数据集中看到的是2977行、156列，这是你论文中提到的不符，能否告知一下这是为什么？

**Comment by mgsky1** [comment]
我想你把这个矩阵转置一下就好了，那就变成了行为道路，列为时间数

**Comment by qiubin1997** [comment]
我知道转置后是论文提到的那样，我想问的是为什么csv文件里一开始 不按照论文中提到的要求显示呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lehaifeng/T-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 上午9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lehaifeng/T-GCN] 关于sz_speed数据集的问题 (#43)





 
我想你把这个矩阵转置一下就好了，那就变成了行为道路，列为时间数
