### ISSUE TITLE
TCN Pytorch 版本是否还未完善？

### ISSUE THREAD

**Issue by csjiezhao** [lehaifeng/T-GCN#46]
您好！
我注意到 TCN 的代码里面最后给出的是 每个units的输出 (batch_size, num_nodes, num_gru_units)，作者是否打算截取最后一个unit 的输出, 并变换成 （batch_size, num_nodes, len_for_predict）?

**Comment by martinwhl** [comment]
The final fully-connected layer is defined in `tasks/supervised.py`.

**Comment by csjiezhao** [comment]
> The final fully-connected layer is defined in `tasks/supervised.py`.

Thanks for your reply. I have another question, that is, the gcn operation in this repo is not implemented as a 2-layer stack (e.i. Eq3 in the paper), right?

**Comment by martinwhl** [comment]
> > The final fully-connected layer is defined in `tasks/supervised.py`.
> 
> Thanks for your reply. I have another question, that is, the gcn operation in this repo is not implemented as a 2-layer stack (e.i. Eq3 in the paper), right?

Duplicate of #14 and #29 .

**Comment by rq12301230** [comment]
> 您好！ 我注意到 TCN 的代码里面最后给出的是 每个units的输出 (batch_size, num_nodes, num_gru_units)，作者是否打算截取最后一个unit 的输出, 并变换成 （batch_size, num_nodes, len_for_predict）?

您好，可以讨论一下pytorch里Epoch应该怎么去调节呢。在哪个程序里可以去调节Epoch

**Comment by martinwhl** [comment]
> > 您好！ 我注意到 TCN 的代码里面最后给出的是 每个units的输出 (batch_size, num_nodes, num_gru_units)，作者是否打算截取最后一个unit 的输出, 并变换成 （batch_size, num_nodes, len_for_predict）?
> 
> 您好，可以讨论一下pytorch里Epoch应该怎么去调节呢。在哪个程序里可以去调节Epoch

Use the `max_epochs` argument, e.g. `python main.py --max_epochs 123`. For more information, please refer to the official documentation of PyTorch Lightning: https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#trainer-flags
