### ISSUE TITLE
How can i use this code in classfication problem?

### ISSUE THREAD

**Issue by DLMU-dh218** [lehaifeng/T-GCN#47]
Sorry to bother you,I have studied your paper and code in recent days.and i am deeply inspired by your idea,During the study period,two questions occour in my mind.
1,if i want to categorize  articles that have references to each other,which part of code do i need to modify?
2,I noticed that the adjency matrix is not only contain 0 and 1,how to understand that?
Looking forward to your reply

**Comment by martinwhl** [comment]
For question 2, the adjacency matrix is computed based on the distances between sensors. For pairs of sensors with longer distances, the corresponding value in the adjacency matrix is smaller.

**Comment by DLMU-dh218** [comment]
thanks for your reply.^ ^
