### ISSUE TITLE
您好，请问A3T-GCN模型可以运行吗，可以的话如何操作呢？

### ISSUE THREAD

**Issue by zycode1561** [lehaifeng/T-GCN#48]

**Comment by lehaifeng** [comment]
Hi there,
The A3T-GCN model shares some packages with the vanilla T-GCN model. If you find anything missing, please refer to [https://github.com/lehaifeng/T-GCN/tree/master/T-GCN/T-GCN-TensorFlow](url)

**Comment by zycode1561** [comment]
> Hi there,
> The A3T-GCN model shares some packages with the vanilla T-GCN model. If you find anything missing, please refer to [https://github.com/lehaifeng/T-GCN/tree/master/T-GCN/T-GCN-TensorFlow](url)

Thank you! I've got it
