### ISSUE TITLE
Problem on T-GCN/T-GCN-PyTorch/utils/data/spatiotemporal_csv_data.py

### ISSUE THREAD

**Issue by RowanLiu97** [lehaifeng/T-GCN#49]
https://github.com/lehaifeng/T-GCN/blob/e92b26a8764576e61b455c053c3ef1780c977321/T-GCN/T-GCN-PyTorch/utils/data/spatiotemporal_csv_data.py#L9
In SpatioTemporalCSVDataModule class, you define the initial method. From your code, you specify the value of the parameter directly rather than specify it by passing the parameter **kwargs。

**Comment by martinwhl** [comment]
https://github.com/lehaifeng/T-GCN/blob/e92b26a8764576e61b455c053c3ef1780c977321/T-GCN/T-GCN-PyTorch/main.py#L50-L52
The parameters are passed via `**vars(args)`. Hope this answers your question.

**Comment by RowanLiu97** [comment]
Thanks for replying!
Yes， the parameters are passed via **vars(args) in code 
`dm = utils.data.SpatioTemporalCSVDataModule(feat_path=DATA_PATHS[args.data]['feat'], 
                                             adj_path=DATA_PATHS[args.data]['adj'], 
                                             **vars(args)) `
however, in this code segment, you set batch_size, seq_len, ... to a constant, rather than assigning them by **vars(args)
```
   def __init__(self, feat_path: str, adj_path: str, batch_size: int = 64,
                 seq_len: int = 12, pre_len: int = 3, 
                 split_ratio: float = 0.8, normalize: bool = True, **kwargs):
```
maybe the code should be as follow:
`    def __init__(self, feat_path: str, adj_path: str, **kwargs):
        super(SpatioTemporalCSVDataModule, self).__init__()
        self._feat_path = feat_path
        self._adj_path = adj_path

        # self.batch_size = batch_size
        # self.seq_len = seq_len
        # self.pre_len = pre_len
        # self.split_ratio = split_ratio
        # self.normalize = normalize
        
        self.batch_size = kwargs['batch_size']
        self.seq_len = kwargs['seq_len']
        self.pre_len = kwargs['pre_len']
        self.split_ratio = kwargs['split_ratio']
        self.normalize = kwargs['normalize']
       
        self._feat = utils.data.functions.load_features(self._feat_path)
        self._feat_max_val = np.max(self._feat)
        self._adj = utils.data.functions.load_adjacency_matrix(self._adj_path)`

**Comment by martinwhl** [comment]
You can try this in your REPL.
```Python
def f(a, b, c=1, d=2, e=3, **kwargs):
    print(a, b, c, d, e)

d = {'c': 3, 'd': 4, 'e': 5}
print(f(1, 2, **d))  # 1 2 3 4 5
```

**Comment by RowanLiu97** [comment]
Thank you! I've got it
