### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by prateikarora** [lehaifeng/T-GCN#5]
Hi. I really liked your paper.
1. Can you provide the link of the online repository from where you took data for your experiments? 
2. https://www.cs.rutgers.edu/~dz220/data.html is this the site for shehnzen data? 
3. where did you get the data for the adjacency matrix data for connectivity among the nodes? Did you do it manually?

**Comment by lehaifeng** [comment]
Hi prateikarora, really thanks for your attention.

The original road-based traffic data set in Shenzhen is non-public according to the data using protocol. The edges in adjacency matrix represent the connection relationship between the roads, which is extracted from the corresponding shapefile of Shenzhen road network.

We did not use the data from https://www.cs.rutgers.edu/~dz220/data.html. Those data sets seem interesting. We will try them in our future works.

**Comment by prateikarora** [comment]
thanks a lot

**Comment by ThomasAFink** [comment]
To create your own matrix this may help: https://github.com/ThomasAFink/osmnx_adjacency_matrix_for_graph_convolutional_networks
