### ISSUE TITLE
how to predict new values

### ISSUE THREAD

**Issue by xpf2333** [lehaifeng/T-GCN#50]
I have a trouble in predicting new values after I trained and evaluated the model. Thank you!

**Comment by martinwhl** [comment]
I'm afraid I can't help you with such little information. Could you please describe your problem in detail?

**Comment by martinwhl** [comment]
If I get it right, you want to run predictions on a new dataset or some unseen data after training. In that case, if you use the PyTorch version of code, you can define your own dataset/`LightningDataModule`, then run `trainer.predict()`. For more information, you may take a look at [the official documentation of PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html?highlight=predict#predict) for references.

**Comment by EnergyYou** [comment]
> I have a trouble in predicting new values after I trained and evaluated the model. Thank you!

Hi! Have you solved this problem?   I don't know how to predict new data. Can you give me some advice? Thank you!!!

**Comment by xpf2333** [comment]
> If I get it right, you want to run predictions on a new dataset or some unseen data after training. In that case, if you use the PyTorch version of code, you can define your own dataset/`LightningDataModule`, then run `trainer.predict()`. For more information, you may take a look at [the official documentation of PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html?highlight=predict#predict) for references.

Thank you for your reply! I use the tensorflow version. Since the code use version 1.x with sess, I dont know how to make predictions in new dataset, but I have sovled this problem. Thank you!

**Comment by xpf2333** [comment]
> > I have a trouble in predicting new values after I trained and evaluated the model. Thank you!
> 
> Hi! Have you solved this problem? I don't know how to predict new data. Can you give me some advice? Thank you!!!

You can try "output_label=sess.run([y_pred],feed_dict={inputs: testX}) ".
