### ISSUE TITLE
About the batch in gcn model

### ISSUE THREAD

**Issue by JONCC2017** [lehaifeng/T-GCN#54]
Hi, Thanks for sharing the codes. I met some problems when try to understand the GCN codes. What is the meaning of batch in GCN. You noted the inputs size as "(batch_size, seq_len, num_nodes)". However in other open srouces program such as dgl. Their inputs to GCN layer nomally is "(num_nodes,feature_dim)". I also try to solve the problem by reading your papers. But i didn't find any solution.
Thank you for your time.

**Comment by martinwhl** [comment]
For the spatiotemporal forecasting problem, a batch consists of multiple samples which contain the temporal features of the whole graph, and the shape of one sample is (seq_len, num_nodes).
