### ISSUE TITLE
A question and solution

### ISSUE THREAD

**Issue by zysyz233** [lehaifeng/T-GCN#56]
Hi,when I use the code in GCN,I meet the error like "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!",and the problem happen to "..\T-GCN-PyTorch\utils\callbacks\base\best_epoch.py", line 51, in on_validation_batch_end if monitor_op(monitor_value, self.best_value):".
Fortunately,i find the solution to solve it,just add ".to(device="cpu")" after "monitor_value = metrics_dict.get(self.monitor, self.best_value)".but I don't know if this revision is rigorous,can you give me some advice?thanks

**Comment by martinwhl** [comment]
Thanks for your attention!
This problem is probably due to the upgrade of PyTorch Lightning or TorchMetrics, as it didn't occur before. The issue is now fixed, and thank you again for your suggestion.

**Comment by zysyz233** [comment]
oh,Your solution is better,and thank you for sharing your code , which is a useful reference for me
