### ISSUE TITLE
老师，请教一下代码中的GCN和GRU模型如何才能运行预测数据集？

### ISSUE THREAD

**Issue by qiubin1997** [lehaifeng/T-GCN#58]
老师，您好！请问一下，论文中提到的baselines中提到的GCN和GRU，在您提供的代码中是如何才能运行，并且预测提供的数据集？希望您可以指点一下，使我可以进一步学习和研究。我保证他们只会用于研究目的。非常感谢您的考虑，期待您的早日回信，万分感谢!
       祝您一切安好！

**Comment by rq12301230** [comment]
> ```
>      老师，您好！请问一下，论文中提到的baselines中提到的GCN和GRU，在您提供的代码中是如何才能运行，并且预测提供的数据集？希望您可以指点一下，使我可以进一步学习和研究。我保证他们只会用于研究目的。非常感谢您的考虑，期待您的早日回信，万分感谢!
>    祝您一切安好！
> ```

同学，请问您解决了这个问题吗？目前我也有一样的疑惑

**Comment by qiubin1997** [comment]
&nbsp; &nbsp; GRU可以运行，GCN还是没办法运行，您有没有解决GCN的运行问题?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lehaifeng/T-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月7日(星期天) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lehaifeng/T-GCN] 老师，请教一下代码中的GCN和GRU模型如何才能运行预测数据集？ (#58)





       老师，您好！请问一下，论文中提到的baselines中提到的GCN和GRU，在您提供的代码中是如何才能运行，并且预测提供的数据集？希望您可以指点一下，使我可以进一步学习和研究。我保证他们只会用于研究目的。非常感谢您的考虑，期待您的早日回信，万分感谢!    祝您一切安好！   
同学，请问您解决了这个问题吗？目前我也有一样的疑惑
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
