### ISSUE TITLE
T-GCN

### ISSUE THREAD

**Issue by xiaodong-chan** [lehaifeng/T-GCN#59]
The hidden variable h and x are concatenated to a variable [h a] first, and then A [h x], which conflicts with the description of the paper.

**Comment by Chrixtar** [comment]
Hello,

you are right.
I found that the complete approach of combining GCN with GRU is different in the paper and the implementation.
The paper proposes to simply stack a 2-layer GCN and a single GRU, i.e., the GCN is used as a form of input preprocessing for the GRU. Both the equations as well as the figures support this understanding.
However, the implementation replaces all matrix multiplications of the GRU with individual graph convolutions on the concatenated input and (reset) hidden state.

Could the authors please clarify why there are these conflicts between paper and code?

Best regards
Chris
