### ISSUE TITLE
Topological tolerance

### ISSUE THREAD

**Issue by bmkor** [lehaifeng/T-GCN#6]
Thanks for the code sharing. 

I got a similar case with traffic speed on road network as data and I convert the road network to line graph for GCN. 

My case got a bit tricky: road network may change; some road may be blocked due to reconstructing. 

My question is what will be the tolerance of the GCN model to edge change? I don’t know how to quantify, but it would be great if you share us your experience. Thanks in advance.

**Comment by lehaifeng** [comment]
Hi, bmkor.  Thanks for your attention.

You ask a very good question. 
In our case, we only considered how robust our model against Gaussian or Poison noise. 
In your case, we think it a problem on dynamic analysis of GCN. You may refer to Dynamic Graph Convolutional Networks (https://arxiv.org/abs/1704.06199). 

We also are working on that, and will release our works after the this work has gotten done!

**Comment by bmkor** [comment]
Hi @lehaifeng, wondering any update?
