### ISSUE TITLE
TGCN with Node level features

### ISSUE THREAD

**Issue by saimanikant62** [lehaifeng/T-GCN#60]
Hi Team,
Thank you for the wonderful work on TGCN. I am planning to use the model in my research project and I was wondering if its possible to incorporate node level features and node level labels which are time varying. My dataset is a panel dataset and the graph keeps evolving at various time intervals. 

I would really appreciate your insight.

Thank you,
Sai

**Comment by martinwhl** [comment]
In our scenario (which is traffic flow forecasting), the features and the labels are also node-level and time-varying. As for dynamic graphs, feeding different adjacency matrices at different time steps may help, but I cannot guarantee the performance of the model.
