### ISSUE TITLE
input_data中的“preprocess_average_data”

### ISSUE THREAD

**Issue by hanhan30** [lehaifeng/T-GCN#65]
请问文件中缺少的preprocess_average_data，大家是如何处理的呀

**Comment by hanhan30** [comment]
就是在A3T-GCN模型中引用了“from input_data import preprocess_data,preprocess_average_data,load_sz_data,load_los_data”
然后咱们给的input_data中无preprocess_average_data

**Comment by lehaifeng** [comment]
preprocess_average_data是之前版本的一次尝试，现有版本实际上还是采用了preprocess_data。
