### ISSUE TITLE
hello author 

### ISSUE THREAD

**Issue by liwentao-123** [lehaifeng/T-GCN#69]
After I had read the KST-GCN paper, I read the code of this paper ,but I have a question is that which file can generate the embedding [sz_kg_transE_embedding20.csv](https://github.com/lehaifeng/T-GCN/blob/master/KST-GCN/data/KG/sz_kg_transE_embedding20.csv)

**Comment by lehaifeng** [comment]
Hi there, the model we used to generate embeddings is the KR-EAR (https://github.com/thunlp/KR-EAR)
