### ISSUE TITLE
Can it be generalised to a directed graph?

### ISSUE THREAD

**Issue by bmkor** [lehaifeng/T-GCN#7]
Wondering if we can apply the graph convolution layer to a directed graph? The Fourier domain may not be well-defined in this case?

**Comment by lehaifeng** [comment]
Hi bmkor, Thanks for your interests

Yes, I think you could do this by taking a non-symmetric normalized adjacency matrix, i.e. D^(-1)*A. In undirected graph case, the matrix is D^(-1/2)*A*D^(-1/2)

You may refer to https://arxiv.org/abs/1703.06103 for more details.
