### ISSUE TITLE
how to consider multiple traffic information?

### ISSUE THREAD

**Issue by xie-kun** [lehaifeng/T-GCN#73]
For T-GCN, in your paper only traffic speed as an example of traffic information in experiment section. If I want to use both traffic speed and flow, how to change the code? Whether concatenate both  traffic speed and flow as a feature matrix X dirictly?

**Comment by lehaifeng** [comment]
Yes, T-GCN can work for multivariate data. You can definitely try the concatenation strategy.

**Comment by Deepyman** [comment]
> Yes, T-GCN can work for multivariate data. You can definitely try the concatenation strategy.

Hi, May I have a little detailed question? I also want to try multiple features, but I am lost in how to make the dataset, and we just need to change GCN part and we don't need to change GRU part right? Because after GCN layer, all the features have already been embedded.
