### ISSUE TITLE
Hi, I have a question about PyTorch version T-GCN, trainer.validate()

### ISSUE THREAD

**Issue by yanyanh5945** [lehaifeng/T-GCN#77]
My pytorch_lightning is 1.2.0. After successfully running the training process. I got "AttributeError: 'Trainer' object has no attribute 'validate'". I think it may related to the version of pl. Do you have any comments on this issue or any suggested version of pl? Thanks!

**Comment by yanyanh5945** [comment]
Sorry that I didn't notice there is a required version for pl. I upgraded pl to 1.3.0, downgraded torchmetrics to 0.3.0, reinstalled setuptools for additional issues. It worked for trainer.validate(dm). However, it seems that I can not still run trainer.test(). Do you have any suggestions on this issue? Thanks!

**Comment by martinwhl** [comment]
Please try the latest version of PL and `torchmetrics`, they should work fine. For API usages, please refer to the documentation of PyTorch Lightning.

**Comment by yanyanh5945** [comment]
Thank you for the reply. I figured out how to run it. Just a reminder that the latest version of PL doesn't work.
