### ISSUE TITLE
How to run GCN model?

### ISSUE THREAD

**Issue by chaojidaxingxin** [lehaifeng/T-GCN#8]
The output'shape of _gconv function(in gcn.py) is [batch*, self._output_dim, self._num_nodes], but the weights['out']'s shape  is [gru_units, pre_len], need to redefine a fully connected layer to generate for GCN?
Thank you very much for uploading your paper's code.
Thank you!

**Comment by lehaifeng** [comment]
HI chaojidaxingxin. Thanks for your attention.

In gcn.py, “y_pred = model.output” can be directly used for the prediction result.

**Comment by chaojidaxingxin** [comment]
output_dim in gcn.py means  is the pre_len in labels?
