### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'mad'

### ISSUE THREAD

**Issue by 13631818862** [lehaifeng/T-GCN#92]
hi, I would like to ask a question.
Among iGCL, in IDGCL.py, the code"self.teacher_ema_updater = utils.EMA(args.mad, args.epochs)" is missing args.mad.
And then this code reported an error "AttributeError: 'Config' object has no attribute 'mad'".
Could you tell me how to use the iGCL with my own dataset?

**Comment by lehaifeng** [comment]
Thank you for the issue, we have added the 'mad' hyperparameter to the configuration.py.
Would you please try it again?
Best

**Comment by 13631818862** [comment]
Thank you for your reply. I successfully ran through your code.
